steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/amplified-asset-426508-e7/apache-image:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'images', 'create', 'apache-image-$COMMIT_SHA', '--source-uri', 'gs://amplified-asset-426508-e7.appspot.com/apache-image-$COMMIT_SHA.tar.gz']
images:
  - 'gcr.io/amplified-asset-426508-e7/apache-image:$COMMIT_SHA'