steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-south1-docker.pkg.dev/amplified-asset-426508-e7/myrepo7/apache-image:latest'
      - './apache/'  # Path to the directory containing Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-south1-docker.pkg.dev/amplified-asset-426508-e7/myrepo7/apache-image:latest'

